from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from app.services.pdf_reports.report_schemas import ReportPayload

try:  # pragma: no cover - optional dependency branch
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    REPORTLAB_AVAILABLE = True
except Exception:  # pragma: no cover - optional dependency branch
    REPORTLAB_AVAILABLE = False


def render_report_pdf(
    output_path: Path,
    payload: ReportPayload,
    *,
    report_type: str,
    generated_by: str,
    filters: dict[str, Any],
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if REPORTLAB_AVAILABLE:
        _render_with_reportlab(output_path, payload, report_type=report_type, generated_by=generated_by, filters=filters)
        return
    output_path.write_bytes(_render_minimal_pdf(payload, report_type=report_type, generated_by=generated_by, filters=filters))


def _render_with_reportlab(
    output_path: Path,
    payload: ReportPayload,
    *,
    report_type: str,
    generated_by: str,
    filters: dict[str, Any],
) -> None:
    doc = SimpleDocTemplate(str(output_path), pagesize=A4, leftMargin=28, rightMargin=28, topMargin=32, bottomMargin=32)
    styles = getSampleStyleSheet()
    story = [
        Paragraph(payload.title, styles["Title"]),
        Spacer(1, 6),
        Paragraph(f"Generated at: {datetime.utcnow().isoformat(timespec='seconds')} UTC", styles["Normal"]),
        Paragraph(f"Generated by: {generated_by}", styles["Normal"]),
        Paragraph(f"Report type: {report_type}", styles["Normal"]),
        Spacer(1, 8),
    ]
    if filters:
        filter_parts = [f"{key}: {value}" for key, value in filters.items()]
        story.append(Paragraph("Filters: " + " | ".join(filter_parts), styles["Normal"]))
        story.append(Spacer(1, 10))

    story.append(Paragraph("Summary", styles["Heading2"]))
    if payload.summary:
        for key, value in payload.summary.items():
            story.append(Paragraph(f"- {key.replace('_', ' ').title()}: {value}", styles["Normal"]))
    else:
        story.append(Paragraph("- No summary metrics available.", styles["Normal"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Details", styles["Heading2"]))
    if payload.rows:
        header_keys = _best_keys(payload.rows)
        table_data = [[key.replace("_", " ").title() for key in header_keys]]
        for row in payload.rows:
            table_data.append([str(row.get(key, "")) for key in header_keys])
        table = Table(table_data, repeatRows=1)
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E2E8F0")),
                    ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#CBD5E1")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                ]
            )
        )
        story.append(table)
    else:
        story.append(Paragraph("No records found for this report.", styles["Normal"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Next Actions", styles["Heading2"]))
    if payload.recommendations:
        for item in payload.recommendations:
            story.append(Paragraph(f"- {item}", styles["Normal"]))
    else:
        story.append(Paragraph("- No immediate action required.", styles["Normal"]))

    def on_page(canvas, doc_obj):  # type: ignore[no-untyped-def]
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.drawRightString(560, 18, f"Page {canvas.getPageNumber()}")
        canvas.restoreState()

    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)


def _best_keys(rows: list[dict[str, Any]]) -> list[str]:
    preferred = [
        "po_number",
        "product",
        "stage",
        "status",
        "priority",
        "shortage_meters",
        "pending_qty",
        "ready_qty",
        "deadline",
        "date",
    ]
    keys = set()
    for row in rows[:30]:
        keys.update(row.keys())
    ordered = [key for key in preferred if key in keys]
    ordered.extend(sorted(key for key in keys if key not in ordered))
    return ordered[:10] or ["message"]


def _render_minimal_pdf(payload: ReportPayload, *, report_type: str, generated_by: str, filters: dict[str, Any]) -> bytes:
    lines = [
        payload.title,
        f"Report type: {report_type}",
        f"Generated by: {generated_by}",
        f"Generated at: {datetime.utcnow().isoformat(timespec='seconds')} UTC",
        f"Filters: {filters or 'None'}",
        "",
        "Summary:",
    ]
    if payload.summary:
        lines.extend(f"- {k}: {v}" for k, v in payload.summary.items())
    else:
        lines.append("- No summary metrics available.")
    lines.append("")
    lines.append("Details:")
    if payload.rows:
        for row in payload.rows[:50]:
            lines.append(" | ".join(f"{k}={v}" for k, v in row.items()))
    else:
        lines.append("No records found for this report.")
    lines.append("")
    lines.append("Next actions:")
    lines.extend(payload.recommendations or ["No immediate action required."])
    text = "\n".join(lines)

    sanitized = text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
    stream = f"BT /F1 9 Tf 36 800 Td 11 TL ({sanitized.replace(chr(10), ') Tj T* (')}) Tj ET"
    stream_bytes = stream.encode("latin-1", errors="replace")
    objects = []
    objects.append(b"<< /Type /Catalog /Pages 2 0 R >>")
    objects.append(b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>")
    objects.append(b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>")
    objects.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    objects.append(f"<< /Length {len(stream_bytes)} >>".encode("ascii") + b"\nstream\n" + stream_bytes + b"\nendstream")

    pdf = bytearray(b"%PDF-1.4\n")
    offsets = []
    for index, obj in enumerate(objects, start=1):
        offsets.append(len(pdf))
        pdf.extend(f"{index} 0 obj\n".encode("ascii"))
        pdf.extend(obj)
        pdf.extend(b"\nendobj\n")
    xref_pos = len(pdf)
    pdf.extend(f"xref\n0 {len(objects)+1}\n".encode("ascii"))
    pdf.extend(b"0000000000 65535 f \n")
    for off in offsets:
        pdf.extend(f"{off:010d} 00000 n \n".encode("ascii"))
    pdf.extend(
        (
            "trailer\n"
            f"<< /Size {len(objects)+1} /Root 1 0 R >>\n"
            "startxref\n"
            f"{xref_pos}\n"
            "%%EOF\n"
        ).encode("ascii")
    )
    return bytes(pdf)

